export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  SESSION_REVOKED: "SESSION_REVOKED",
  FORBIDDEN: "FORBIDDEN",
  AI_DISABLED: "AI_DISABLED",
  DESTRUCTIVE_DISABLED: "DESTRUCTIVE_DISABLED",
  ACTION_NOT_ALLOWED: "ACTION_NOT_ALLOWED",
  ACTION_ALREADY_EXECUTED: "ACTION_ALREADY_EXECUTED",
  ACTION_EXPIRED: "ACTION_EXPIRED",
  REFERENCE_PENDING: "REFERENCE_PENDING",
  ACTION_DEPENDENCY_PENDING: "ACTION_DEPENDENCY_PENDING",
  NOT_FOUND: "NOT_FOUND",
  ACCOUNT_ARCHIVED: "ACCOUNT_ARCHIVED",
  DUPLICATE_BUDGET: "DUPLICATE_BUDGET",
  EMAIL_IN_USE: "EMAIL_IN_USE",
  RATE_LIMITED: "RATE_LIMITED",
  MARKET_UNAVAILABLE: "MARKET_UNAVAILABLE",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
