export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  SESSION_REVOKED: "SESSION_REVOKED",
  FORBIDDEN: "FORBIDDEN",
  AI_DISABLED: "AI_DISABLED",
  NOT_FOUND: "NOT_FOUND",
  ACCOUNT_ARCHIVED: "ACCOUNT_ARCHIVED",
  DUPLICATE_BUDGET: "DUPLICATE_BUDGET",
  EMAIL_IN_USE: "EMAIL_IN_USE",
  RATE_LIMITED: "RATE_LIMITED",
  MARKET_UNAVAILABLE: "MARKET_UNAVAILABLE",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
